name: 'My Action'
description: 'A sample GitHub Action'
outputs:
  result:
    description: 'Share this result with other steps in the same job'
    value: ${{ steps.dostuff.outputs.result }}
runs:
  using: 'composite'
  steps:
    - id: dostuff
      run: echo "::set-output name=result::1234"
      shell: bash
